---
- name: Create VPN user (no login shell)
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /usr/sbin/nologin
    create_home: true
    state: present
  when: login_with_otp | bool

- name: Configure key files in client configuration
  ansible.builtin.command:
    cmd: ./easyrsa --batch build-client-full {{ username }} nopass
    chdir: "{{ easyrsa_dir }}"
    creates: "{{ easyrsa_dir }}/pki/issued/{{ username }}.crt"

- name: Check created server certificate and key file
  ansible.builtin.stat:
    path: "{{ item }}"
  loop:
    - "{{ easyrsa_dir }}/pki/issued/{{ username }}.crt"
    - "{{ easyrsa_dir }}/pki/private/{{ username }}.key"
  register: key_files

- name: Fail the playbook if any file is missing
  ansible.builtin.assert:
    that: 
      - item.stat.exists | bool
  loop: "{{ key_files.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Copy OpenVPN sample client configuration file
  ansible.builtin.copy:
    src: "/usr/share/doc/openvpn/examples/sample-config-files/client.conf"
    dest: "/tmp/{{ username }}.ovpn"
    remote_src: yes

- name: Configure client configuration file
  ansible.builtin.lineinfile:
    path: "/tmp/{{ username }}.ovpn"
    regexp: '^remote my-server-1 1194$'
    line: "remote {{ public_ip }} 1194"

- name: Comment out TLS auth
  ansible.builtin.replace:
    path: "/tmp/{{ username }}.ovpn"
    regexp: '^tls-auth (.+$)'
    replace: '#tls-auth \1'

- name: Read ca.crt
  ansible.builtin.slurp:
    src: "{{ easyrsa_dir }}/pki/ca.crt"
  register: ca_crt

- name: Read client crt
  ansible.builtin.slurp:
    src: "{{ easyrsa_dir }}/pki/issued/{{ username }}.crt"
  register: client_crt

- name: Read client key
  ansible.builtin.slurp:
    src: "{{ easyrsa_dir }}/pki/private/{{ username }}.key"
  register: client_key

- name: Remove inline ca/cert/key directives
  ansible.builtin.lineinfile:
    path: "/tmp/{{ username }}.ovpn"
    regexp: "{{ item }}"
    state: absent
  loop:
    - '^ca ca.crt$'
    - '^cert client.crt$'
    - '^key client.key$'

- name: Embed ca, cert, key inline
  ansible.builtin.blockinfile:
    path: "/tmp/{{ username }}.ovpn"
    block: |
      <ca>
      {{ ca_crt.content | b64decode }}
      </ca>
      <cert>
      {{ client_crt.content | b64decode }}
      </cert>
      <key>
      {{ client_key.content | b64decode }}
      </key>
    marker: ""

- name: Add auth-user-pass directive
  ansible.builtin.lineinfile:
    path: "/tmp/{{ username }}.ovpn"
    line: "auth-user-pass"
    insertafter: EOF
  when: login_with_otp | bool
