---
- name: Create OpenVPN client on Ubuntu
  hosts: server_OpenVPN
  become: true

  vars:
    login_with_otp: false

  roles:
    - role: create_client
      vars:
        username: "{{ openvpn_username }}"
        public_ip: "{{ public_ip_address }}"
        login_with_otp: "{{ login_with_otp }}"
  
  tasks:
    - name: Get OpenVPN configuration file
      ansible.builtin.fetch:
        src: "/tmp/{{ openvpn_username }}.ovpn"
        dest: "./{{ openvpn_username }}.ovpn"
        flat: yes
