---
- name: Create OpenVPN client on Rocky Linux 9
  hosts: server_OpenVPN
  become: true
  roles:
    - role: create_client
      vars:
        username: "{{ openvpn_username }}"
        public_ip: "{{ public_ip_address }}"
  
  tasks:
    - name: Get OpenVPN configuration file
      ansible.builtin.fetch:
        src: "/tmp/{{ openvpn_username }}.ovpn"
        dest: "./{{ openvpn_username }}.ovpn"
        flat: yes
